import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, CalendarDays, Check, ChevronDown, ChevronUp, Clock3, Heart, MapPin, Menu, Plus, Search, SlidersHorizontal, Star, Users, X, Scale, Send, Sparkles } from 'lucide-react';
import './styles.css';
import './override.css';
import './b2b.css';
import './tour-detail.css';

const images = [
  'https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'https://images.pexels.com/photos/1365425/pexels-photo-1365425.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'https://images.pexels.com/photos/2662116/pexels-photo-2662116.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'https://images.pexels.com/photos/2101187/pexels-photo-2101187.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'https://images.pexels.com/photos/733162/pexels-photo-733162.jpeg?auto=compress&cs=tinysrgb&w=1200'
];
const rawTrips = [
  ['Алтай','Высота, тишина, Катунь','Ника Белова','12–18 августа','7 дней','74 000','Небольшая группа','мягкий'],['Камчатка','Дышать вулканами','Саша Котов','3–10 сентября','8 дней','129 000','До 8 человек','активный'],['Байкал','Зимний Байкал без спешки','Лера Соколова','15–20 февраля','6 дней','68 000','Комфорт+','мягкий'],['Кавказ','Лето в горах Осетии','Тимур Дзагуров','22–27 июля','6 дней','59 000','Для новичков','мягкий'],['Карелия','Ладожские шхеры на каяках','Маша Рябова','9–13 июня','5 дней','52 000','Вода и лес','активный'],['Дагестан','Аулы, море и горные дороги','Аминат Алиева','4–10 октября','7 дней','63 000','Гастрономический','мягкий'],['Кольский','За северным сиянием','Аня Фёдорова','18–23 января','6 дней','79 000','Зимняя сказка','мягкий'],['Курилы','Край света: Итуруп','Илья Третьяков','11–18 сентября','8 дней','118 000','Малая группа','активный'],['Сахалин','Океанский ветер и маяки','Катя Юдина','6–12 августа','7 дней','91 000','Новый маршрут','мягкий'],['Архыз','Тропа к горным озёрам','Руслан Кипкеев','19–24 июня','6 дней','57 000','Пеший маршрут','активный'],['Калининград','Балтика в межсезонье','Даша Неретина','13–17 ноября','5 дней','48 000','Город и природа','мягкий'],['Крым','Тёплые тропы Восточного Крыма','Егор Миронов','2–7 мая','6 дней','54 000','Море и горы','активный'],['Урал','По следам каменного пояса','Варя Антонова','10–15 июля','6 дней','55 000','Для любознательных','мягкий'],['Чукотка','Там, где начинается Арктика','Макс Ровный','7–16 августа','10 дней','167 000','Экспедиция','активный'],['Приморье','Тигриные тропы Сихотэ-Алиня','Юра Семёнов','5–11 октября','7 дней','72 000','Заповедный край','активный'],['Адыгея','Каньоны и альпийские луга','Соня Бабаева','16–21 мая','6 дней','51 000','Для новичков','мягкий'],['Плато Путорана','Озёра среди базальтов','Витя Норд','1–9 августа','9 дней','145 000','Экспедиция','активный'],['Териберка','На край земли за китами','Оля Савина','24–28 июня','5 дней','67 000','Баренцево море','мягкий'],['Якутия','Ленские столбы и белые ночи','Кира Ойун','15–22 июля','8 дней','96 000','Открытие сезона','активный'],['Татарстан','Волжский уикенд со вкусом','Ринат Хасанов','12–14 сентября','3 дня','31 000','Городской','мягкий']
];
const guidePortraits=['https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=300','https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=300','https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=300','https://images.pexels.com/photos/1183472/pexels-photo-1183472.jpeg?auto=compress&cs=tinysrgb&w=300'];
const trips = rawTrips.map((t,i)=>({id:i+1,region:t[0],title:t[1],guide:t[2],guideRole:i%2?'местный проводник и фотограф':'гид-исследователь, влюблённый в регион',guidePhoto:guidePortraits[i%guidePortraits.length],dates:t[3],days:t[4],price:t[5],tag:t[6],level:t[7],rating:(4.8+(i%3)/10).toFixed(1),reviews:18+i*3,image:images[i%images.length],description:`Это путешествие про ${t[0].toLowerCase()} без суеты: красивые дороги, честные разговоры и места, куда не доезжают большие туристические автобусы. Мы собрали маршрут так, чтобы каждый день оставлял воздух для личных открытий.`, program:[['День 1 · Знакомство',`Встречаемся, заселяемся и за ужином знакомимся с группой. Гид расскажет о ритме путешествия, а вечером выйдем на первую прогулку.`],['День 2 · Главный маршрут',`После спокойного завтрака отправимся по самой красивой дороге региона. Будут короткие прогулки, остановки для фотографий и пикник с местными продуктами.`],['День 3 · Свой темп',`Сегодня больше свободы: небольшая тропа, время побыть наедине с природой и общий ужин с историями из прошлого дня.`],['День 4 · Особенное место',`Доберёмся до точки, которую гид считает личной любимицей. В программе — видовая прогулка, чай и много времени, чтобы просто смотреть вокруг.`],['Финальный день · Домой',`Позавтракаем, обменяемся снимками и впечатлениями. Трансфер доставит вас к месту отправления.`]],gallery:[images[(i+1)%6],images[(i+2)%6],images[(i+3)%6]]}));
const monthTerms = {май:'мая',июнь:'июня',июль:'июля',август:'августа',сентябрь:'сентября',октябрь:'октября',ноябрь:'ноября',январь:'января',февраль:'февраля'};

function App(){
 const [query,setQuery]=useState(''); const [filter,setFilter]=useState('Все'); const [level,setLevel]=useState('Все'); const [date,setDate]=useState('Любые даты'); const [modal,setModal]=useState(null); const [guideForm,setGuideForm]=useState(false); const [liked,setLiked]=useState([]); const [compare,setCompare]=useState([]); const [filters,setFilters]=useState(false); const [toast,setToast]=useState('');
 const showToast=t=>{setToast(t);setTimeout(()=>setToast(''),2200)};
 const shown=useMemo(()=>trips.filter(t=>(filter==='Все'||t.region===filter)&&(level==='Все'||t.level===level)&&(date==='Любые даты'||t.dates.toLowerCase().includes(monthTerms[date]))&&`${t.title} ${t.region} ${t.guide}`.toLowerCase().includes(query.toLowerCase())),[query,filter,level,date]);
 const toggleLike=(e,id)=>{e?.stopPropagation();setLiked(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])};
 const toggleCompare=(e,id)=>{e?.stopPropagation();if(compare.includes(id))return setCompare(x=>x.filter(v=>v!==id));if(compare.length===3)return showToast('Можно сравнить до трёх путешествий');setCompare(x=>[...x,id])};
 const regions=['Все','Алтай','Камчатка','Байкал','Кавказ','Карелия','Дагестан','Кольский'];
 return <main><header className="topbar"><a className="logo" href="#top">Дорога<span>·</span></a><nav><a href="#catalog">Путешествия</a><a href="#story">О проекте</a><a href="#guides">Гиды</a></nav><div className="top-actions"><button onClick={()=>setGuideForm(true)}>Стать гидом <ArrowRight size={15}/></button><button className="mobile-menu" onClick={()=>showToast('Меню открыто')}><Menu/></button></div></header>
 <section className="hero" id="top"><div className="hero-copy"><p className="kicker"><Sparkles size={14}/> Авторские путешествия по России</p><h1>Не просто увидеть.<br/><em>Почувствовать место.</em></h1><p>Выбирайте путь, за которым стоит человек: с любимыми тропами, историями и заботой о каждой детали.</p><a href="#catalog" className="lime-btn">Найти своё путешествие <ArrowRight size={18}/></a><div className="hero-stats"><span><b>120+</b> гидов</span><span><b>47</b> регионов</span><span><b>4.9</b> средняя оценка</span></div></div><div className="hero-art"><img src="https://images.pexels.com/photos/691668/pexels-photo-691668.jpeg?auto=compress&cs=tinysrgb&w=1400" alt="Горный пейзаж"/><div className="hero-photo-overlay"></div><div className="hero-note"><MapPin size={16}/><div><b>Там, где хочется остаться</b><small>Новые маршруты каждую неделю</small></div></div></div></section>
 <section className="catalog" id="catalog"><div className="section-title"><div><p className="kicker dark">Выберите свой ритм</p><h2>Ближайшие путешествия</h2></div><p>Двадцать маршрутов от гидов, которые<br/>знают свою землю как дом.</p></div>
 <div className="controls"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Куда хочется?"/></label><div className="region-scroll">{regions.map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?'selected':''}>{x}</button>)}</div><button className={filters?'filter open':'filter'} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={16}/> Фильтры</button></div>
 {filters&&<div className="filterbox"><div><span>Формат поездки</span><button className={level==='Все'?'on':''} onClick={()=>setLevel('Все')}>Любой</button><button className={level==='мягкий'?'on':''} onClick={()=>setLevel('мягкий')}>Спокойный</button><button className={level==='активный'?'on':''} onClick={()=>setLevel('активный')}>Активный</button></div><div className="date-picker"><span>Когда поедем?</span>{['Любые даты','май','июнь','июль','август','сентябрь','октябрь','ноябрь','январь','февраль'].map(d=><button key={d} className={date===d?'on':''} onClick={()=>setDate(d)}>{d}</button>)}</div><button className="reset" onClick={()=>{setFilter('Все');setLevel('Все');setDate('Любые даты');setQuery('')}}>Сбросить</button></div>}
 <p className="found">Найдено: <b>{shown.length} путешествий</b></p><div className="trip-grid">{shown.map((t,i)=><TripCard key={t.id} trip={t} liked={liked.includes(t.id)} compared={compare.includes(t.id)} open={()=>setModal(t)} like={toggleLike} compare={toggleCompare} index={i}/>)}</div>
 {!shown.length&&<div className="empty"><MapPin/><h3>По этому запросу пока тихо</h3><button onClick={()=>{setQuery('');setFilter('Все');setLevel('Все')}}>Показать все маршруты</button></div>}
 </section><section className="b2b" id="story"><div className="b2b-copy"><p className="kicker">Для компаний и команд</p><h2>Соберём путешествие,<br/><em>которое станет вашим.</em></h2><p>Корпоративный выезд, путешествие для клиентов или камерный ретрит — подберём регион, гида, темп и детали под задачу вашей команды.</p><button className="b2b-action" onClick={()=>showToast('Спасибо! Запрос на индивидуальный маршрут принят.')}>Обсудить маршрут <ArrowRight size={17}/></button></div><div className="b2b-side"><div className="b2b-card"><span className="b2b-icon">01</span><div><b>От 6 человек</b><p>Организуем группы любого масштаба</p></div></div><div className="b2b-card"><span className="b2b-icon">02</span><div><b>Личный куратор</b><p>На связи до, во время и после поездки</p></div></div><div className="b2b-card"><span className="b2b-icon">03</span><div><b>Всё под ключ</b><p>Логистика, проживание и впечатления</p></div></div><p className="b2b-note"><Sparkles size={15}/> Ответим с идеей маршрута в течение рабочего дня</p></div></section>
 <footer><a className="logo" href="#top">Дорога<span>·</span></a><p>Авторские путешествия и выезды для команд.</p><small>© 2026 · Сделано с уважением к России</small></footer>
 {compare.length>0&&<CompareBar ids={compare} remove={id=>setCompare(x=>x.filter(v=>v!==id))} open={()=>setModal({compare:true})}/>} {toast&&<div className="toast"><Check size={16}/>{toast}</div>} {modal&&<TripModal trip={modal} close={()=>setModal(null)} liked={liked} like={toggleLike} compare={compare} toggleCompare={toggleCompare} />} {guideForm&&<GuideForm close={()=>setGuideForm(false)} done={()=>{setGuideForm(false);showToast('Анкета отправлена. Мы скоро напишем вам!')}}/>}</main>
}
function TripCard({trip,open,liked,compared,like,compare,index}){return <article className="card" onClick={open} onKeyDown={e=>e.key==='Enter'&&open()} tabIndex="0" style={{animationDelay:`${index*35}ms`}}><div className="card-image"><img src={trip.image} alt={`${trip.region}: ${trip.title}`}/><span>{trip.tag}</span><button aria-label="Добавить в избранное" className={liked?'heart active':'heart'} onClick={e=>like(e,trip.id)}><Heart size={18} fill={liked?'currentColor':'none'}/></button><button aria-label="Сравнить" className={compared?'compare active':'compare'} onClick={e=>compare(e,trip.id)}><Scale size={16}/></button></div><div className="card-copy"><div className="card-line"><p>{trip.region}</p><span><Star size={13} fill="currentColor"/>{trip.rating} <i>({trip.reviews})</i></span></div><h3>{trip.title}</h3><div className="guide-preview"><img src={trip.guidePhoto} alt={trip.guide}/><div><b>{trip.guide}</b><span>{trip.guideRole}</span></div></div><div className="card-meta"><span><CalendarDays size={14}/>{trip.dates}</span><span><Clock3 size={14}/>{trip.days}</span></div><div className="card-price"><div><small>от</small><strong>{trip.price} ₽</strong></div><span>Смотреть <ArrowRight size={16}/></span></div></div></article>}
function CompareBar({ids,remove,open}){let list=trips.filter(t=>ids.includes(t.id));return <div className="compare-bar"><div><Scale size={18}/><b>Сравнение</b>{list.map(t=><span key={t.id}>{t.title}<button onClick={()=>remove(t.id)}><X size={13}/></button></span>)}</div><button onClick={open}>Сравнить {ids.length} <ArrowRight size={16}/></button></div>}
function TripModal({trip,close,liked,like,compare,toggleCompare}){const [openDay,setOpenDay]=useState(0);const [allReviews,setAllReviews]=useState(false);if(trip.compare){let chosen=trips.filter(t=>compare.includes(t.id));return <div className="veil" onMouseDown={close}><div className="compare-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><p className="kicker dark">Ваш выбор</p><h2>Сравнение маршрутов</h2><div className="compare-table"><div>Маршрут</div>{chosen.map(t=><b key={t.id}>{t.title}<small>{t.region}</small></b>)}<div>Длительность</div>{chosen.map(t=><span key={t.id}>{t.days}</span>)}<div>Стоимость</div>{chosen.map(t=><span key={t.id}>от {t.price} ₽</span>)}<div>Оценка</div>{chosen.map(t=><span key={t.id}>★ {t.rating}</span>)}</div></div></div>}
const reviews=[['Марина, Москва','Это была редкая поездка, в которой всё сложилось: место, люди и ощущение, что тебя очень бережно ведут по новому миру.'],['Илья, Санкт-Петербург','Гид знает буквально каждый поворот и при этом даёт много свободы. Привёз домой сотню фотографий и огромное желание вернуться.'],['Алина, Казань','Красиво организовано, без гонки и лишней суеты. Особенно запомнились вечерние разговоры и маленькие остановки не из путеводителя.'],['Никита, Екатеринбург','Смело рекомендую тем, кто хочет увидеть регион живым, а не поставить галочки в списке.']];
return <div className="veil" onMouseDown={close}><article className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><div className="modal-head"><img src={trip.image} alt=""/><div><p>{trip.region}</p><h2>{trip.title}</h2><span><Star size={15} fill="currentColor"/> {trip.rating} · {trip.reviews} отзывов</span></div></div><div className="modal-grid"><div className="details"><p className="intro">{trip.description} Внутри — комфортные ночёвки, продуманная логистика и небольшая группа людей, которым тоже интересно смотреть внимательнее.</p><div className="gallery">{trip.gallery.map((src,i)=><img key={i} src={src} alt="Впечатления из путешествия"/>)}</div><section className="program-section"><p className="kicker dark">По дням и без спешки</p><h3>Программа путешествия</h3><p className="sub">Нажмите на день, чтобы увидеть детали маршрута.</p><div className="accordion">{trip.program.map((day,i)=><div className={openDay===i?'day expanded':'day'} key={day[0]}><button onClick={()=>setOpenDay(openDay===i?-1:i)}><span>{day[0]}</span>{openDay===i?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button>{openDay===i&&<div><p>{day[1]}</p><img src={trip.gallery[i%3]} alt="Деталь программы"/></div>}</div>)}</div></section><h3>Отзывы путешественников</h3><div className="reviews">{reviews.slice(0,allReviews?4:2).map(r=><blockquote key={r[0]}><Star size={14} fill="currentColor"/><p>«{r[1]}»</p><footer>{r[0]}</footer></blockquote>)}</div><button className="all-reviews" onClick={()=>setAllReviews(!allReviews)}>{allReviews?'Скрыть отзывы':'Все отзывы'} <ArrowRight size={16}/></button></div><aside><div className="booking"><span>Стоимость от</span><strong>{trip.price} ₽</strong><small>за человека</small><hr/><p><CalendarDays size={16}/>{trip.dates}</p><p><Users size={16}/>до 10 путешественников</p><button className="book" onClick={()=>alert('Заявка отправлена! Гид свяжется с вами.')}>Оставить заявку <Send size={16}/></button><button className={liked.includes(trip.id)?'save active':'save'} onClick={e=>like(e,trip.id)}><Heart size={16} fill={liked.includes(trip.id)?'currentColor':'none'}/>{liked.includes(trip.id)?'В избранном':'Сохранить'}</button><button className={compare.includes(trip.id)?'save active':'save'} onClick={e=>toggleCompare(e,trip.id)}><Scale size={16}/>{compare.includes(trip.id)?'В сравнении':'Сравнить'}</button></div><div className="guide"><img src={trip.guidePhoto} alt={trip.guide}/><div><b>{trip.guide}</b><span>{trip.guideRole}</span></div><button onClick={()=>alert(`Написать гиду ${trip.guide}`)}><ArrowRight size={16}/></button></div></aside></div></article></div>}
function GuideForm({close,done}){return <div className="veil" onMouseDown={close}><div className="guide-form" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><p className="kicker dark">Присоединяйтесь к сообществу</p><h2>Стать гидом<br/><em>«Дороги»</em></h2><p>Расскажите немного о себе — мы свяжемся, чтобы обсудить ваши маршруты.</p><label>Ваше имя<input placeholder="Например, Мария"/></label><label>Телефон или Telegram<input placeholder="+7 000 000-00-00"/></label><label>Регион, который вы знаете<input placeholder="Например, Алтай"/></label><button className="guide-submit" onClick={done}>Отправить анкету <ArrowRight size={16}/></button></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
